name: ace-c-ios
options:
  bundleIdPrefix: C.ACE
  deploymentTarget:
    iOS: 14.0
  generateEmptyDirectories: true
packages:
  OHHTTPStubs:
    url: https://github.com/AliSoftware/OHHTTPStubs.git
    exactVersion: 9.1.0
fileGroups:
  - .gitignore
  - README.md
  - ARCHITECTURE.md
  - .swiftlint.yml
  - project.yml
  - Dangerfile.swift

targets:
  App:
    platform: iOS
    type: application
    sources:
      - Sources/
      - Sample/
    postBuildScripts:
      - script: |
                if which swiftlint >/dev/null; then
                  swiftlint autocorrect --format
                  swiftlint
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
  Tests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - Tests/
      - path: Sources/Models
      - path: Sources/Extensions
    scheme:
      testTargets:
        - Tests
      gatherCoverageData: true
    dependencies:
        - package: OHHTTPStubs
          product: OHHTTPStubsSwift
        - package: OHHTTPStubs
          product: OHHTTPStubs
        
  UITests:
    platform: iOS
    type: bundle.ui-testing
    sources:
      - UITests/
    scheme:
      testTargets:
        - UITests
      gatherCoverageData: true
