name: 2108-ace-c-ios
options:
  bundleIdPrefix: C.ACE
  deploymentTarget:
    iOS: 14.0
  generateEmptyDirectories: true

targets:
  2108-ace-c-ios:
    platform: iOS
    type: application
    sources:
      - Sources/
      - .gitignore
      - README.md
      - .swiftlint.yml
    postBuildScripts:
      - script: |
                if which swiftlint >/dev/null; then
                  swiftlint
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
  2108-ace-c-iosTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - Tests/
    scheme:
      testTargets:
        - 2108-ace-c-iosTests
      gatherCoverageData: true
  2108-ace-c-iosUITests:
    platform: iOS
    type: bundle.ui-testing
    sources:
      - UITests/
    scheme:
      testTargets:
        - 2108-ace-c-iosUITests
      gatherCoverageData: true
