name: Testing CI

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install xcodegen
        run: brew install xcodegen
      - name: Generate .xcodeproj
        run: xcodegen
      - uses: mxcl/xcodebuild@v1
