name: Testing CI

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin
      DEVELOPER_DIR: /Applications/Xcode_12.4.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Checkout yonaskolb/Mint
        uses: actions/checkout@v2
        with:
          repository: yonaskolb/Mint
          path: Mint
      - name: Build Mint
        run: swift run mint install yonaskolb/mint
        working-directory: ./Mint
      - run: mint --version
      - name: Cache Mint packages
        uses: actions/cache@v2
        with:
          path: mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-
      - name: Generate .xcodeproj
        run: make xcodeproj
      - name: application test
        run: |
              set -o pipefail &&
              xcodebuild -project ace-c-ios.xcodeproj -scheme Tests -configuration Debug -sdk iphonesimulator -destination "name=iPhone 12" ENABLE_TESTABILITY=YES clean test | xcpretty -c
