# This is a basic workflow to help you get started with Actions

name: Testing CI

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - iOS
        xcode:
          - ^12
    runs-on: macos-latest
    steps:
      - uses: mxcl/xcodebuild@v1
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: test # default = `test`
          code-coverage: true # default = `false`
          warnings-as-errors: true # default = `false`
          configuration: TEST # no default, ie. `xcodebuild` decides itself
