name: Testing CI

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: yonaskolb/Mint
          path: Mint
      - name: Build Mint
        run: sudo make
        working-directory: ./Mint
      - name: Remove Mint/
        run: rm -rf Mint/
        working-directory: ./2108-ace-c-ios
      - name: Generate .xcodeproj
        run: make xcodeproj
      - name: application test
        run: |
              set -o pipefail
              xcodebuild build-for-testing test-without-building -project ace-c-ios.xcodeproj -scheme Tests -configuration Debug -sdk iphonesimulator -destination "name=iPhone 12" ENABLE_TESTABILITY=YES | xcpretty -c
