name: Testing CI

# Controls when the workflow will run
on:
  pull_request:
    branches:
    - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $PATH 
      # 一旦Homebrewでインストール
      - name: Install Mint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/yonaskolb/Mint.git -b $(MINT_VERSION)
	            cd Mint/
	            ls
	            swift build --disable-sandbox -c release --arch x86_64
	            mkdir -p /usr/local/bin
	            cp -f .build/apple/Products/Release/mint /usr/local/bin/mint
	            cd ..
	            rm -rf Mint/
      - name: Generate .xcodeproj
        run: make xcodeproj
      - name: application test
        run: |
              set -o pipefail
              xcodebuild build-for-testing test-without-building -project ace-c-ios.xcodeproj -scheme Tests -configuration Debug -sdk iphonesimulator -destination "name=iPhone 12" ENABLE_TESTABILITY=YES | xcpretty -c
